config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'static#welcome', as: 'welcome'
  get 'search', to: 'static#search', as: 'search'
  post 'search', to: 'static#results'

  delete '/', to: 'sessions#destroy'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'

  get 'user/home', to: 'users#show', as: 'home'
  delete 'user/home', to: 'users#destroy'
  get 'user/signup', to: 'users#new', as: 'signup'
  post 'user/signup', to: 'users#create'
  get 'user/edit', to: 'users#edit', as: 'edit'
  patch 'user/edit', to: 'users#update'

  get 'game/:slug', to: 'games#show', as: 'game'

  get 'genre/:slug', to: 'genres#show', as: 'genre'

  get 'mode/:slug', to: 'modes#show', as: 'mode'

  get 'user/new_game', to: 'user_games#new', as: 'new_played'
  post 'user/new_game', to: 'user_games#create'
  get 'user/:slug', to: 'user_games#show', as: 'played'
  patch 'user/:slug', to: 'user_games#update'
  delete 'user/:slug', to: 'user_games#destroy'
  get 'user/:slug/edit', to: 'user_games#edit', as: 'edit_played'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :user_games
    has_many :users, through: :user_games
    has_many :game_genres
    has_many :genres, through: :game_genres
    has_many :game_modes
    has_many :modes, through: :game_modes

    def self.all_alph
        self.order("title")
    end

    def rating
        (self.user_games.sum("rating").to_f / self.rating_count).round(2)
    end

    def rating_count
        self.user_games.count
    end

end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
    belongs_to :game
    belongs_to :genre
end

app/models/game_mode.rb
class GameMode < ApplicationRecord
    belongs_to :game
    belongs_to :mode
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres
    has_many :games, through: :game_genres

    def self.all_alph
        self.order("name")
    end

end

app/models/mode.rb
class Mode < ApplicationRecord
    has_many :game_modes
    has_many :games, through: :game_modes
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_games
    has_many :games, through: :user_games
    has_secure_password
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :name, length: {in: 4..20}
    validates :password, presence: true
    validates :password, length: {in: 6..20}
end

app/models/user_game.rb
class UserGame < ApplicationRecord
    belongs_to :user
    belongs_to :game
    validates :rating, presence: true
    validates :rating, numericality: {in: 0..100}
    validates :review, presence: true
    validates :review, length: {minimum: 4}
    validates :hours_played, presence: true
    validates :hours_played, numericality: {minimum: 0}
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def show
        @game = Game.find_by(slug: params[:slug])
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def show
        @genre = Genre.find_by(slug: params[:slug])
    end

end

app/controllers/modes_controller.rb
class ModesController < ApplicationController

    def show
        @mode = Mode.find_by(slug: params[:slug])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      user = User.find_by(name: params[:user][:name])
      if user.try(:authenticate, params[:user][:password])
        session[:user_id] = user.id
        session[:user_name] = user.name
        redirect_to home_path
      else
        flash[:message] = ["Incorrect Login Information.","Please Try Again."]
        redirect_to login_path
      end
    end
  
    def destroy
      session.delete(:user_id)
      flash[:message] = ["Successfully Logged Out."]
      redirect_to welcome_path
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def welcome
        render :welcome
    end

    def search
        render :search
    end

    def results
        unless params[:q].blank?
            flash[:search_term] = params[:q]
            flash[:search_games] = Game.all_alph.where("title like ?", "%#{params[:q]}%").limit(10).map {|game| {title: game.title, slug: game.slug}}
            flash[:search_genres] = Genre.all_alph.where("name like ?", "%#{params[:q]}%").limit(5).map {|genre| {name: genre.name, slug: genre.slug}}
            flash[:search_modes] = Mode.where("name like ?", "%#{params[:q]}%").map {|mode| {name: mode.name, slug: mode.slug}}
        end
        redirect_to search_path
    end

end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController
    before_action :require_login, only: [:show, :new, :create, :edit, :update, :destroy]
    before_action :find_ug, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
        @ug = UserGame.new
    end

    def create
        if UserGame.find_by(user_id: @user.id, game_id: params[:user_game][:game_id])
            flash[:message] = ["You already have a game page for this game."]
            redirect_to new_played_path
        else
            @ug = UserGame.new(ug_params)
            if @ug.save
                redirect_to played_path(slug: @ug.game.slug)
            else
                render :new
            end
        end
    end

    def edit
    end

    def update
        @ug.update_attributes(ug_params)
        if @ug.save
            redirect_to played_path(slug: @ug.game.slug)
        else
            render :edit
        end
    end

    def destroy
        @ug.destroy
        redirect_to home_path
    end

    private

    def ug_params
        params[:user_game][:user_id] = session[:user_id]
        params[:user_game][:game_id] ||= @ug.game.id
        params.require(:user_game).permit(:game_id, :user_id, :rating, :review, :hours_played)
    end

    def find_ug
        @ug = UserGame.find_by(user_id: @user.id, game_id: Game.find_by(slug: params[:slug]).id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
    end

    def create
        user = User.new(user_params)
        if user.save
            flash[:message] = ["Account Successfully Created.", "Please Log In."]
            redirect_to login_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        @user.update_attributes(user_params)
        if @user.save
            flash[:message] = ["Account Successfully Updated."]
            redirect_to home_path
        else
            render :edit
        end
    end

    def destroy
        UserGame.where(user_id: session[:user_id]).destroy_all
        @user.destroy
        flash[:message] = ["The account for #{session[:user_name]} has been successfully deleted."]
        session.delete(:user_id)
        session.delete(:user_name)
        redirect_to welcome_path
    end

    private

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation, :favorite_game, :favorite_genre, :favorite_mode)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_genres_helper.rb
module GameGenresHelper
end

app/helpers/game_modes_helper.rb
module GameModesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<div class="third-wrapper">
    <div class="third">
        <%= image_tag "https://images.igdb.com/igdb/image/upload/t_cover_big/#{@game.cover_url}", height: "300" %>
    </div>
    <div class="third">
        <p>
            <b>Released:</b><br><%= Time.at(@game.released.to_i).strftime('%m/%d/%Y') %>
        </p>
        <br>
        <p>
            <b>Genres:</b><br>
            <% @game.genres.each do |genre| %>
                <%= link_to genre.name, genre_path(slug: genre.slug) %><br>
            <% end %>
        </p>
        <br>
        <p>
            <b>Game Modes:</b><br>
            <% @game.modes.each do |mode| %>
                <%= link_to mode.name, mode_path(slug: mode.slug) %><br>
            <% end %>
        </p>
    </div>
    <div class="third">
        <% if @game.rating_count > 0 %>
            <p><span class="large-nums"><%= @game.rating.round(2) %></span><br><b>GameReview Rating</b><br>(based on <%= @game.rating_count %> total ratings)</p><br>
        <% end %>
        <% if @game.critic_rating %>
            <p><span class="large-nums"><%= @game.critic_rating.round(2) %></span><br><b>Critic Rating</b><br>(based on <%= @game.critic_rating_count %> total ratings)</p><br>
        <% end %>
        <p><span class="large-nums"><%= @game.igdb_rating.round(2) %></span><br><b>IGDB Rating</b><br>(based on <%= @game.igdb_rating_count %> total ratings)</p>
    </div>
</div>
<div class="text-wrapper">
    <h2>Summary:</h2>
    <p><%= @game.summary %></p>
    <p><%= @game.story %></p>
</div>
<br>
<% if @game.rating_count > 0 %>
    <div class="text-wrapper">
        <h2>Reviews:</h2>
    </div>
    <% @game.user_games.each do |review| %>
        <div class="review-wrapper">
            <div class="rating"><%= review.rating %></div>
            <h3><%= review.user.name %></h3>
            <p><%= review.review %></p>
        </div>
    <% end %>
<% end %>

app/views/genres/show.html.erb
<h1>Games in the '<%= @genre.name %>' Genre:</h1>
<div class="content-wrapper-left">
    <ul>
    <% @genre.games.each do |game| %>
        <li><%= link_to game.title, game_path(slug: game.slug) %></li>
    <% end %>
    </ul>
</div>

app/views/modes/show.html.erb
<h1>Games Featuring '<%= @mode.name %>' Mode:</h1>
<div class="content-wrapper-left">
    <ul>
    <% @mode.games.each do |game| %>
        <li><%= link_to game.title, game_path(slug: game.slug) %></li>
    <% end %>
    </ul>
</div>

app/views/user_games/_form.html.erb
Hours Played: <%= f.number_field :hours_played %>
Rating: <%= f.number_field :rating %>
Review: <%= f.text_area :review, size: "50x5" %>
<%= f.submit "Save Game!", class: "button" %>

app/views/user_games/edit.html.erb
<%= render "layouts/flash" %>
<h1><%= @user.name %>'s Game Page for '<%= @ug.game.title %>'</h1>
<div class="content-wrapper">
    <%= form_for @ug, url: played_path do |f| %>
        <%= render partial: "form", locals: {f: f} %>
    <% end %>
</div>

app/views/user_games/new.html.erb
<%= render "layouts/flash" %>
<h1>Start a New Game!</h1>
<div class="content-wrapper">
    <%= form_for @ug, url: new_played_path do |f| %>
        <p>Game: <%= f.collection_select :game_id, Game.all_alph, :id, :title, {include_blank: true} %></p>
        <%= render partial: "form", locals: {f: f} %>
    <% end %>
</div>

app/views/user_games/show.html.erb
<h1><%= @ug.user.name %>'s Game Page for '<%= @ug.game.title %>'</h1>
<div class="content-wrapper-left" style="max-width: 500px;">
    <p>Hours Played: <%= @ug.hours_played %></p>
    <p>Rating: <%= @ug.rating %></p>
    <p>Review: <%= @ug.review %></p>
    <p><%= button_to 'Edit Game Page', edit_played_path(slug: @ug.game.slug), method: :get, class: "button" %></p>
    <p><%= button_to 'Delete Game Page', played_path(slug: @ug.game.slug), method: :delete, class: "button", data: { confirm: 'Are you sure you want to delete your game page?' } %></p>
</div>

app/views/users/_form.html.erb
Name (4-20 characters): <%= f.text_field :name %> *<br>
Password (6-20 characters): <%= f.password_field :password %> *<br>
Confirm Password: <%= f.password_field :password_confirmation %> *<br>
<p>(* - Required Fields)</p><br>
<div class="select-mod">
    <%= f.collection_select :favorite_genre, Genre.all_alph, :id, :name, {prompt: "Select Favorite Genre..."} %><br>
</div>
<div class="select-mod">
    <%= f.collection_select :favorite_mode, Mode.all, :id, :name, {prompt: "Select Favorite Game Mode..."} %><br>
</div>
<div class="select-mod">
    <%= f.collection_select :favorite_game, Game.all_alph, :id, :title, {prompt: "Select Favorite Game..."} %><br>
</div>
<%= f.submit class: "button" %><br>

app/views/users/edit.html.erb
<%= render "layouts/flash" %>
<h1>Edit User</h1>
<div class="content-wrapper">
    <%= form_for @user, url: edit_path do |f| %>
        <%= render partial: "form", locals: {f: f} %>
    <% end %>
    <%= button_to 'Delete User', home_path, method: :delete, class: "button", data: { confirm: 'Are you sure you want to delete your account?' } %>
</div>

app/views/users/new.html.erb
<%= render "layouts/flash" %>
<h1>New User Signup</h1>
<div class="content-wrapper">
    <%= form_for User.new, url: signup_path do |f| %>
        <%= render partial: "form", locals: {f: f} %>
    <% end %>
</div>

app/views/users/show.html.erb
<h1>Welcome, <%= session[:user_name] %>!</h1>
<div class="content-wrapper">
    <h3><%= link_to "Start a New Game!", new_played_path %></h3>
</div>
<br><br>
<div class="content-wrapper-left">
    <h3>Your Favorites:</h3>
    <ul>
        <% if @user.favorite_game %>
            <li>Game: <%= link_to Game.find(@user.favorite_game).title, game_path(slug: Game.find(@user.favorite_game).slug) %></li>
        <% else %>
            <li>Game: <%= link_to "Choose a Favorite Game!", edit_path %></li>
        <% end %>
        <% if @user.favorite_genre %>
            <li>Genre: <%= link_to Genre.find(@user.favorite_genre).name, genre_path(slug: Genre.find(@user.favorite_genre).slug) %></li>
        <% else %>
            <li>Genre: <%= link_to "Choose a Favorite Genre!", edit_path %></li>
        <% end %>
        <% if @user.favorite_mode %>
            <li>Game Mode: <%= link_to Mode.find(@user.favorite_mode).name, mode_path(slug: Mode.find(@user.favorite_mode).slug) %></li>
        <% else %>
            <li>Game Mode: <%= link_to "Choose a Favorite Game Mode!", edit_path %></li>
        <% end %>
    </ul>
</div>
<br><br>
<div class="content-wrapper-left">
    <h3>Your Game Pages:</h3>
    <ul>
        <% @user.user_games.each do |ug| %>
            <li><%= link_to ug.game.title, played_path(slug: ug.game.slug) %></li>
        <% end %>
    </ul>
</div>