config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'static#welcome', as: 'welcome'
  get 'search', to: 'static#search', as: 'search'
  post 'search', to: 'static#results'

  delete '/', to: 'sessions#destroy'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'

  get 'user/home', to: 'users#show', as: 'home'
  delete 'user/home', to: 'users#destroy'
  get 'user/signup', to: 'users#new', as: 'signup'
  post 'user/signup', to: 'users#create'
  get 'user/edit', to: 'users#edit', as: 'edit'
  patch 'user/edit', to: 'users#update'

  get 'game/:slug', to: 'games#show', as: 'game'

  get 'genre/:slug', to: 'genres#show', as: 'genre'

  get 'mode/:slug', to: 'modes#show', as: 'mode'

  get 'user/new_game', to: 'user_games#new', as: 'new_played'
  post 'user/new_game', to: 'user_games#create'
  get 'user/:slug', to: 'user_games#show', as: 'played'
  patch 'user/:slug', to: 'user_games#update'
  delete 'user/:slug', to: 'user_games#destroy'
  get 'user/:slug/edit', to: 'user_games#edit', as: 'edit_played'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :user_games
    has_many :users, through: :user_games
    has_many :game_genres
    has_many :genres, through: :game_genres
    has_many :game_modes
    has_many :modes, through: :game_modes

    def self.all_alph
        self.order("title")
    end

    def rating
        (self.user_games.sum("rating").to_f / self.rating_count).round(2)
    end

    def rating_count
        self.user_games.count
    end

end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
    belongs_to :game
    belongs_to :genre
end

app/models/game_mode.rb
class GameMode < ApplicationRecord
    belongs_to :game
    belongs_to :mode
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres
    has_many :games, through: :game_genres

    def self.all_alph
        self.order("name")
    end

end

app/models/mode.rb
class Mode < ApplicationRecord
    has_many :game_modes
    has_many :games, through: :game_modes
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_games
    has_many :games, through: :user_games
    has_secure_password
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :name, length: {in: 4..20}
    validates :password, presence: true
    validates :password, length: {in: 6..20}
end

app/models/user_game.rb
class UserGame < ApplicationRecord
    belongs_to :user
    belongs_to :game
    validates :rating, presence: true
    validates :rating, numericality: {in: 0..100}
    validates :review, presence: true
    validates :review, length: {minimum: 4}
    validates :hours_played, presence: true
    validates :hours_played, numericality: {minimum: 0}
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def show
        @game = Game.find_by(slug: params[:slug])
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    def show
        @genre = Genre.find_by(slug: params[:slug])
    end

end

app/controllers/modes_controller.rb
class ModesController < ApplicationController

    def show
        @mode = Mode.find_by(slug: params[:slug])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show, :edit, :update, :destroy]

    def show
    end

    def new
    end

    def create
        user = User.new(user_params)
        if user.save
            flash[:message] = ["Account Successfully Created.", "Please Log In."]
            redirect_to login_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        @user.update_attributes(user_params)
        if @user.save
            flash[:message] = ["Account Successfully Updated."]
            redirect_to home_path
        else
            render :edit
        end
    end

    def destroy
        UserGame.where(user_id: session[:user_id]).destroy_all
        @user.destroy
        flash[:message] = ["The account for #{session[:user_name]} has been successfully deleted."]
        session.delete(:user_id)
        session.delete(:user_name)
        redirect_to welcome_path
    end

    private

    def user_params
        params.require(:user).permit(:name, :password, :password_confirmation, :favorite_game, :favorite_genre, :favorite_mode)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_genres_helper.rb
module GameGenresHelper
end

app/helpers/game_modes_helper.rb
module GameModesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/user_games_helper.rb
module UserGamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:message] %>
    <div class="flash">
        <% flash[:message].each do |msg| %>
            <%= msg %><br>
        <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <%= link_to search_path do %>
        <div class="navbar-item">Search</div>
      <% end %>
      <% if logged_in? %>
        <%= link_to home_path do %>
          <div class="navbar-item">Home</div>
        <% end %>
        <%= link_to edit_path do %>
          <div class="navbar-item">My Account</div>
        <% end %>
        <%= link_to welcome_path, method: :delete do %>
          <div class="navbar-item">Log Out</div>
        <% end %>
      <% else %>
        <%= link_to login_path do %>
          <div class="navbar-item">Log In</div>
        <% end %>
        <%= link_to signup_path do %>
          <div class="navbar-item">Sign Up</div>
        <% end %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>